theme: jekyll-theme-cayman
title: Interactive Simulation Library (ISL)The libRAINBOW homepage
description: This is python code library for rigging, setting up and running simulations in Jupyter notebooks