"""Elastic, pressure, external-force, and global assembly tests."""

import unittest

from unit_tests.test_soft_support import _SoftBodyTests


class TestSoftForceAssembly(unittest.TestCase):
    test_uniform_tet_scale_produces_central_restoring_forces = _SoftBodyTests.test_uniform_tet_scale_produces_central_restoring_forces
    test_octahedron_scale_has_axis_aligned_restoring_forces_and_zero_center_force = _SoftBodyTests.test_octahedron_scale_has_axis_aligned_restoring_forces_and_zero_center_force
    test_tet_translation_has_zero_elastic_force = _SoftBodyTests.test_tet_translation_has_zero_elastic_force
    test_tet_rigid_rotation_about_each_coordinate_axis_has_zero_force = _SoftBodyTests.test_tet_rigid_rotation_about_each_coordinate_axis_has_zero_force
    test_unit_cube_shear_force_restores_material_coordinates = _SoftBodyTests.test_unit_cube_shear_force_restores_material_coordinates
    test_single_tet_force_assembly_matches_shape_function_formula = _SoftBodyTests.test_single_tet_force_assembly_matches_shape_function_formula
    test_affine_multi_tet_patch_test_has_zero_interior_force = _SoftBodyTests.test_affine_multi_tet_patch_test_has_zero_interior_force
    test_internal_forces_conserve_linear_and_angular_momentum = _SoftBodyTests.test_internal_forces_conserve_linear_and_angular_momentum
    test_tetrahedron_order_does_not_change_assembled_force = _SoftBodyTests.test_tetrahedron_order_does_not_change_assembled_force
    test_force_is_restoring_for_small_stretch = _SoftBodyTests.test_force_is_restoring_for_small_stretch
    test_pressure_face_set_uses_linear_surface_fem_forces = _SoftBodyTests.test_pressure_face_set_uses_linear_surface_fem_forces
    test_pressure_forces_match_current_area_vectors_and_per_face_pressures = _SoftBodyTests.test_pressure_forces_match_current_area_vectors_and_per_face_pressures
    test_pressure_forces_are_translation_invariant = _SoftBodyTests.test_pressure_forces_are_translation_invariant
    test_pressure_forces_rotate_covariantly_and_scalar_matches_per_face_values = _SoftBodyTests.test_pressure_forces_rotate_covariantly_and_scalar_matches_per_face_values
    test_uniform_pressure_on_closed_tetrahedron_has_zero_resultant = _SoftBodyTests.test_uniform_pressure_on_closed_tetrahedron_has_zero_resultant
    test_empty_pressure_face_set_has_zero_force = _SoftBodyTests.test_empty_pressure_face_set_has_zero_force
    test_pressure_boundary_input_is_validated = _SoftBodyTests.test_pressure_boundary_input_is_validated
    test_state_and_load_inputs_reject_nonfinite_values = _SoftBodyTests.test_state_and_load_inputs_reject_nonfinite_values
    test_external_nodal_forces_are_persistent_and_can_be_cleared = _SoftBodyTests.test_external_nodal_forces_are_persistent_and_can_be_cleared
    test_total_force_is_additive_for_elastic_pressure_body_and_external_terms = _SoftBodyTests.test_total_force_is_additive_for_elastic_pressure_body_and_external_terms
    test_external_force_input_shape_is_validated = _SoftBodyTests.test_external_force_input_shape_is_validated
    test_jax_and_numpy_assembled_forces_agree_on_multi_tet_mesh = _SoftBodyTests.test_jax_and_numpy_assembled_forces_agree_on_multi_tet_mesh
    test_jax_and_numpy_force_paths_agree_for_both_materials = _SoftBodyTests.test_jax_and_numpy_force_paths_agree_for_both_materials
    test_jax_and_numpy_pressure_forces_agree_on_multiple_faces = _SoftBodyTests.test_jax_and_numpy_pressure_forces_agree_on_multiple_faces
    test_directional_force_matches_independent_finite_difference = _SoftBodyTests.test_directional_force_matches_independent_finite_difference
    test_jax_directional_force_matches_finite_difference = _SoftBodyTests.test_jax_directional_force_matches_finite_difference
