"""Constitutive laws, invariants, and material-parameter tests."""

import unittest

from unit_tests.test_soft_support import _SoftBodyTests


class TestSoftConstitutive(unittest.TestCase):
    test_material_parameters_reject_nonphysical_edge_cases = _SoftBodyTests.test_material_parameters_reject_nonphysical_edge_cases
    test_constitutive_stress_is_zero_at_rest_for_both_models = _SoftBodyTests.test_constitutive_stress_is_zero_at_rest_for_both_models
    test_both_models_have_expected_linear_elastic_limit = _SoftBodyTests.test_both_models_have_expected_linear_elastic_limit
    test_constitutive_energy_gradient_matches_pk1_stress = _SoftBodyTests.test_constitutive_energy_gradient_matches_pk1_stress
    test_constitutive_objectivity_and_isotropy_invariants = _SoftBodyTests.test_constitutive_objectivity_and_isotropy_invariants
    test_constitutive_edge_states_are_finite_and_stable_model_handles_inversion = _SoftBodyTests.test_constitutive_edge_states_are_finite_and_stable_model_handles_inversion
    test_reference_configuration_has_zero_force_and_expected_mass = _SoftBodyTests.test_reference_configuration_has_zero_force_and_expected_mass
    test_stable_neo_hookean_has_zero_rest_force_and_finite_inversion_force = _SoftBodyTests.test_stable_neo_hookean_has_zero_rest_force_and_finite_inversion_force
    test_material_force_is_negative_energy_gradient = _SoftBodyTests.test_material_force_is_negative_energy_gradient
    test_jax_autodiff_energy_gradient_agrees_with_analytical_pk1 = _SoftBodyTests.test_jax_autodiff_energy_gradient_agrees_with_analytical_pk1
