"""Time integration, constraints, and backend agreement tests."""

import unittest

from unit_tests.test_soft_support import _SoftBodyTests


class TestSoftTimeStepping(unittest.TestCase):
    test_fixed_vertices_are_preserved_by_time_step = _SoftBodyTests.test_fixed_vertices_are_preserved_by_time_step
    test_semi_implicit_step_moves_under_gravity = _SoftBodyTests.test_semi_implicit_step_moves_under_gravity
    test_implicit_bfgs_accepts_settings_and_preserves_rest_state = _SoftBodyTests.test_implicit_bfgs_accepts_settings_and_preserves_rest_state
    test_implicit_bfgs_converges_under_gravity_for_both_materials = _SoftBodyTests.test_implicit_bfgs_converges_under_gravity_for_both_materials
    test_jax_semi_implicit_step_matches_numpy = _SoftBodyTests.test_jax_semi_implicit_step_matches_numpy
    test_jax_implicit_bfgs_matches_numpy_native_solver = _SoftBodyTests.test_jax_implicit_bfgs_matches_numpy_native_solver
    test_jax_and_numpy_timestep_agree_with_external_and_body_forces = _SoftBodyTests.test_jax_and_numpy_timestep_agree_with_external_and_body_forces
    test_jax_and_numpy_restore_initially_displaced_fixed_vertices = _SoftBodyTests.test_jax_and_numpy_restore_initially_displaced_fixed_vertices
    test_step_validates_timestep_method_and_gravity = _SoftBodyTests.test_step_validates_timestep_method_and_gravity
    test_implicit_settings_are_validated = _SoftBodyTests.test_implicit_settings_are_validated
    test_fixed_vertex_setter_validates_indices_and_updates_constraints = _SoftBodyTests.test_fixed_vertex_setter_validates_indices_and_updates_constraints
    test_implicit_bfgs_converges_with_pressure_and_external_loading = _SoftBodyTests.test_implicit_bfgs_converges_with_pressure_and_external_loading
    test_all_fixed_implicit_system_is_supported_by_numpy_and_jax = _SoftBodyTests.test_all_fixed_implicit_system_is_supported_by_numpy_and_jax
    test_jax_fixed_vertex_setter_updates_device_constraints = _SoftBodyTests.test_jax_fixed_vertex_setter_updates_device_constraints
