"""Time integration, constraints, and backend agreement tests."""

import unittest

from unit_tests.test_soft_support import _SoftBodyTests


class TestSoftTimeStepping(unittest.TestCase):
    test_fixed_vertices_are_preserved_by_time_step = _SoftBodyTests.test_fixed_vertices_are_preserved_by_time_step
    test_semi_implicit_step_moves_under_gravity = _SoftBodyTests.test_semi_implicit_step_moves_under_gravity
    test_implicit_bfgs_accepts_settings_and_preserves_rest_state = _SoftBodyTests.test_implicit_bfgs_accepts_settings_and_preserves_rest_state
    test_implicit_bfgs_converges_under_gravity_for_both_materials = _SoftBodyTests.test_implicit_bfgs_converges_under_gravity_for_both_materials
    test_jax_semi_implicit_step_matches_numpy = _SoftBodyTests.test_jax_semi_implicit_step_matches_numpy
    test_jax_implicit_bfgs_matches_numpy_native_solver = _SoftBodyTests.test_jax_implicit_bfgs_matches_numpy_native_solver
    test_jax_and_numpy_timestep_agree_with_external_and_body_forces = _SoftBodyTests.test_jax_and_numpy_timestep_agree_with_external_and_body_forces
    test_jax_and_numpy_restore_initially_displaced_fixed_vertices = _SoftBodyTests.test_jax_and_numpy_restore_initially_displaced_fixed_vertices
    test_step_validates_timestep_method_and_gravity = _SoftBodyTests.test_step_validates_timestep_method_and_gravity
    test_implicit_settings_are_validated = _SoftBodyTests.test_implicit_settings_are_validated
    test_all_directional_residual_strategies_converge = _SoftBodyTests.test_all_directional_residual_strategies_converge
    test_fixed_vertex_setter_validates_indices_and_updates_constraints = _SoftBodyTests.test_fixed_vertex_setter_validates_indices_and_updates_constraints
    test_implicit_bfgs_converges_with_pressure_and_external_loading = _SoftBodyTests.test_implicit_bfgs_converges_with_pressure_and_external_loading
    test_implicit_failure_keeps_finite_state_and_honors_raise_on_failure = _SoftBodyTests.test_implicit_failure_keeps_finite_state_and_honors_raise_on_failure
    test_all_fixed_implicit_system_is_supported_by_numpy_and_jax = _SoftBodyTests.test_all_fixed_implicit_system_is_supported_by_numpy_and_jax
    test_jax_fixed_vertex_setter_updates_device_constraints = _SoftBodyTests.test_jax_fixed_vertex_setter_updates_device_constraints
    test_jax_state_setter_invalidates_device_cache = _SoftBodyTests.test_jax_state_setter_invalidates_device_cache
    test_state_getters_return_copies_and_setters_synchronize_state = _SoftBodyTests.test_state_getters_return_copies_and_setters_synchronize_state
    test_jax_unsynchronized_step_keeps_solver_on_device_until_getter_or_sync = _SoftBodyTests.test_jax_unsynchronized_step_keeps_solver_on_device_until_getter_or_sync
    test_jax_implicit_reduced_line_search_step_remains_finite = _SoftBodyTests.test_jax_implicit_reduced_line_search_step_remains_finite
    test_dirichlet_positions_and_velocities_are_enforced_by_both_steppers = _SoftBodyTests.test_dirichlet_positions_and_velocities_are_enforced_by_both_steppers
