"""Geometry, mesh validity, and canonical baseline tests."""

import unittest

from unit_tests.test_soft_support import _SoftBodyTests


class TestSoftGeometry(unittest.TestCase):
    test_regular_tet_is_centered_and_equiangular = _SoftBodyTests.test_regular_tet_is_centered_and_equiangular
    test_baseline_factories_share_scale_and_create_finite_bodies = _SoftBodyTests.test_baseline_factories_share_scale_and_create_finite_bodies
    test_numpy_beam_mesh_is_oriented_without_external_geometry_dependencies = _SoftBodyTests.test_numpy_beam_mesh_is_oriented_without_external_geometry_dependencies
    test_mesh_rejects_degenerate_and_inverted_reference_tetrahedra = _SoftBodyTests.test_mesh_rejects_degenerate_and_inverted_reference_tetrahedra
    test_mesh_validates_shapes_indices_finiteness_and_density = _SoftBodyTests.test_mesh_validates_shapes_indices_finiteness_and_density
    test_boundary_faces_cancel_interior_faces_and_have_no_duplicates = _SoftBodyTests.test_boundary_faces_cancel_interior_faces_and_have_no_duplicates
    test_boundary_faces_reject_malformed_elements = _SoftBodyTests.test_boundary_faces_reject_malformed_elements
    test_baseline_loads_have_expected_bending_stretch_compression_and_twist_resultants = _SoftBodyTests.test_baseline_loads_have_expected_bending_stretch_compression_and_twist_resultants
